# GIT
alias gd='git diff'
alias gco='git checkout'
alias gs='git status'
alias gl='git pull'
alias gp='git push'
alias gsync='git pull; git push'
alias gwc='git whatchanged -p --abbrev-commit --pretty=medium'
alias current_branch='git branch | grep "^\*" | cut -d" " -f2'
alias gwip='save-changes-to-git-and-push-to-remote'
