bindkey -M viins "^@" set-mark-command
bindkey -M viins "^A" beginning-of-line
bindkey -M viins "^B" backward-char
bindkey -M viins "^D" delete-char-or-list
bindkey -M viins "^E" end-of-line
bindkey -M viins "^F" forward-char
bindkey -M viins "^G" send-break
bindkey -M viins "^H" backward-delete-char
bindkey -M viins "^J" accept-line
bindkey -M viins "^K" kill-line
bindkey -M viins "^L" clear-screen
bindkey -M viins "^M" accept-line
bindkey -M viins "^N" down-line-or-history
bindkey -M viins "^O" accept-line-and-down-history
bindkey -M viins "^P" up-line-or-history
bindkey -M viins "^Q" push-line
bindkey -M viins "^S" history-incremental-search-forward
bindkey -M viins "^U" kill-whole-line
bindkey -M viins "^V" quoted-insert
bindkey -M viins "^W" backward-kill-word
bindkey -M viins "^X^B" vi-match-bracket
bindkey -M viins "^X^E" edit-command-line
bindkey -M viins "^X^F" vi-find-next-char
bindkey -M viins "^X^J" vi-join
bindkey -M viins "^X^K" kill-buffer
bindkey -M viins "^X^N" infer-next-history
bindkey -M viins "^X^O" overwrite-mode
bindkey -M viins "^X^R" _read_comp
bindkey -M viins "^X^U" undo
bindkey -M viins "^X^V" vi-cmd-mode
bindkey -M viins "^X^X" exchange-point-and-mark
bindkey -M viins "^X*" expand-word
bindkey -M viins "^X=" what-cursor-position
bindkey -M viins "^X?" _complete_debug
bindkey -M viins "^XC" _correct_filename
bindkey -M viins "^XG" list-expand
bindkey -M viins "^Xa" _expand_alias
bindkey -M viins "^Xc" _correct_word
bindkey -M viins "^Xd" _list_expansions
bindkey -M viins "^Xe" _expand_word
bindkey -M viins "^Xg" list-expand
bindkey -M viins "^Xh" _complete_help
bindkey -M viins "^Xm" _most_recent_file
bindkey -M viins "^Xn" _next_tags
bindkey -M viins "^Xr" history-incremental-search-backward
bindkey -M viins "^Xs" history-incremental-search-forward
bindkey -M viins "^Xt" _complete_tag
bindkey -M viins "^Xu" undo
bindkey -M viins "^X~" _bash_list-choices
bindkey -M viins "^Y" yank
bindkey -M viins "^[^D" list-choices
bindkey -M viins "^[^G" send-break
bindkey -M viins "^[^H" backward-kill-word
bindkey -M viins "^[^I" self-insert-unmeta
bindkey -M viins "^[^J" self-insert-unmeta
bindkey -M viins "^[^L" clear-screen
bindkey -M viins "^[^M" self-insert-unmeta
bindkey -M viins "^[^[" sudo-command-line
bindkey -M viins "^[^_" copy-prev-word
bindkey -M viins "^[ " expand-history
bindkey -M viins "^[!" expand-history
bindkey -M viins "^[\"" quote-region
bindkey -M viins "^[\$" spell-word
bindkey -M viins "^['" quote-line
bindkey -M viins "^[," _history-complete-newer
bindkey -M viins "^[-" neg-argument
bindkey -M viins "^[." insert-last-word
bindkey -M viins "^[/" _history-complete-older
bindkey -M viins "^[0" digit-argument
bindkey -M viins "^[1" digit-argument
bindkey -M viins "^[2" digit-argument
bindkey -M viins "^[3" digit-argument
bindkey -M viins "^[4" digit-argument
bindkey -M viins "^[5" digit-argument
bindkey -M viins "^[6" digit-argument
bindkey -M viins "^[7" digit-argument
bindkey -M viins "^[8" digit-argument
bindkey -M viins "^[9" digit-argument
bindkey -M viins "^[<" beginning-of-buffer-or-history
bindkey -M viins "^[>" end-of-buffer-or-history
bindkey -M viins "^[?" which-command
bindkey -M viins "^[A" accept-and-hold
bindkey -M viins "^[B" backward-word
bindkey -M viins "^[C" capitalize-word
bindkey -M viins "^[D" kill-word
bindkey -M viins "^[F" forward-word
bindkey -M viins "^[G" get-line
bindkey -M viins "^[H" run-help
bindkey -M viins "^[L" down-case-word
bindkey -M viins "^[N" history-search-forward
bindkey -M viins "^[OA" history-substring-search-up
bindkey -M viins "^[OB" history-substring-search-down
bindkey -M viins "^[OC" forward-char
bindkey -M viins "^[OD" backward-char
bindkey -M viins "^[OF" end-of-line
bindkey -M viins "^[OH" beginning-of-line
bindkey -M viins "^[P" history-search-backward
bindkey -M viins "^[Q" push-line
bindkey -M viins "^[S" spell-word
bindkey -M viins "^[T" transpose-words
bindkey -M viins "^[U" up-case-word
bindkey -M viins "^[W" copy-region-as-kill
bindkey -M viins "^[[1;5C" forward-word
bindkey -M viins "^[[1;5D" backward-word
bindkey -M viins "^[[200~" bracketed-paste
bindkey -M viins "^[[2~" overwrite-mode
bindkey -M viins "^[[3~" delete-char
bindkey -M viins "^[[5~" up-line-or-history
bindkey -M viins "^[[6~" down-line-or-history
bindkey -M viins "^[[A" up-line-or-history
bindkey -M viins "^[[B" down-line-or-history
bindkey -M viins "^[[C" forward-char
bindkey -M viins "^[[D" backward-char
bindkey -M viins "^[[Z" reverse-menu-complete
bindkey -M viins "^[_" insert-last-word
bindkey -M viins "^[a" accept-and-hold
bindkey -M viins "^[b" backward-word
bindkey -M viins "^[d" kill-word
bindkey -M viins "^[f" forward-word
bindkey -M viins "^[g" get-line
bindkey -M viins "^[h" run-help
bindkey -M viins "^[m" copy-prev-shell-word
bindkey -M viins "^[n" history-search-forward
bindkey -M viins "^[p" history-search-backward
bindkey -M viins "^[q" push-line
bindkey -M viins "^[s" spell-word
bindkey -M viins "^[t" transpose-words
bindkey -M viins "^[u" up-case-word
bindkey -M viins "^[w" kill-region
bindkey -M viins "^[x" execute-named-cmd
bindkey -M viins "^[y" yank-pop
bindkey -M viins "^[z" execute-last-named-cmd
bindkey -M viins "^[|" vi-goto-column
bindkey -M viins "^[~" _bash_complete-word
bindkey -M viins "^[^?" backward-kill-word
bindkey -M viins "^_" undo
bindkey -M viins " " magic-space
